package examen.pkg1_alessandroreyes;

import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        tf_user = new javax.swing.JTextField();
        pf_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_r_log = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jd_crear = new javax.swing.JDialog();
        jd_Ctutor = new javax.swing.JDialog();
        jd_Cexamen = new javax.swing.JDialog();
        jd_tutor = new javax.swing.JDialog();
        jd_estudiante = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        Crear = new javax.swing.JMenu();
        jmi_Calumno = new javax.swing.JMenuItem();
        jmi_Ctutor = new javax.swing.JMenuItem();
        jmi_Cexamen = new javax.swing.JMenuItem();

        btn_login.setText("Log in");
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });

        btn_r_log.setText("Regresar");
        btn_r_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_r_logMouseClicked(evt);
            }
        });

        jLabel1.setText("Ingrese su usuario:");

        jLabel2.setText("Ingrese su contraseña:");

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jd_loginLayout.createSequentialGroup()
                            .addComponent(btn_r_log)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pf_pass, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_user, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_login, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(btn_r_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout jd_crearLayout = new javax.swing.GroupLayout(jd_crear.getContentPane());
        jd_crear.getContentPane().setLayout(jd_crearLayout);
        jd_crearLayout.setHorizontalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jd_crearLayout.setVerticalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_CtutorLayout = new javax.swing.GroupLayout(jd_Ctutor.getContentPane());
        jd_Ctutor.getContentPane().setLayout(jd_CtutorLayout);
        jd_CtutorLayout.setHorizontalGroup(
            jd_CtutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_CtutorLayout.setVerticalGroup(
            jd_CtutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_CexamenLayout = new javax.swing.GroupLayout(jd_Cexamen.getContentPane());
        jd_Cexamen.getContentPane().setLayout(jd_CexamenLayout);
        jd_CexamenLayout.setHorizontalGroup(
            jd_CexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_CexamenLayout.setVerticalGroup(
            jd_CexamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_tutorLayout = new javax.swing.GroupLayout(jd_tutor.getContentPane());
        jd_tutor.getContentPane().setLayout(jd_tutorLayout);
        jd_tutorLayout.setHorizontalGroup(
            jd_tutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_tutorLayout.setVerticalGroup(
            jd_tutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_estudianteLayout = new javax.swing.GroupLayout(jd_estudiante.getContentPane());
        jd_estudiante.getContentPane().setLayout(jd_estudianteLayout);
        jd_estudianteLayout.setHorizontalGroup(
            jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_estudianteLayout.setVerticalGroup(
            jd_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login.setText("Log in");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        jMenuBar1.add(Login);

        Crear.setText("Crear");

        jmi_Calumno.setText("Crear Alumno");
        jmi_Calumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CalumnoActionPerformed(evt);
            }
        });
        Crear.add(jmi_Calumno);

        jmi_Ctutor.setText("Crear Tutor");
        Crear.add(jmi_Ctutor);

        jmi_Cexamen.setText("Crear Examen");
        Crear.add(jmi_Cexamen);

        jMenuBar1.add(Crear);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        this.setVisible(false);
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }//GEN-LAST:event_LoginMouseClicked

    private void btn_r_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_r_logMouseClicked
        jd_login.setModal(false);
        jd_login.setVisible(false);
        pf_pass.setText("");
        tf_user.setText("");
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_btn_r_logMouseClicked

    private void jmi_CalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CalumnoActionPerformed
        this.setVisible(false);
        jd_crear.setModal(true);
        jd_crear.pack();
        jd_crear.setLocationRelativeTo(this);
        jd_crear.setVisible(true);
    }//GEN-LAST:event_jmi_CalumnoActionPerformed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        boolean v = false;
        try {
            if (tf_user.getText().isEmpty() && pf_pass.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese algo");
            } else {
                for (int i = 0; i < tutor.size(); i++) {
                    if (tf_user.getText().equals(tutor.get(i).getUsuario())
                            && pf_pass.getText().equals(tutor.get(i).getContraseña())) {
                        v = true;
                        this.setVisible(false);
                        jd_tutor.setModal(true);
                        jd_tutor.pack();
                        jd_tutor.setLocationRelativeTo(this);
                        jd_tutor.setVisible(true);
                        
                        break;
                    }
                }
                for (int i = 0; i < estudiantes.size(); i++) {
                    if (tf_user.getText().equals(estudiantes.get(i).getUsuario())
                            && pf_pass.getText().equals(estudiantes.get(i).getContraseña())) {
                        v = true;
                        this.setVisible(false);
                        jd_estudiante.setModal(true);
                        jd_estudiante.pack();
                        jd_estudiante.setLocationRelativeTo(this);
                        jd_estudiante.setVisible(true);
                        break;
                    }
                }
                
                if (v == false) {
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta");
                    pf_pass.setText("");
                    tf_user.setText("");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
            pf_pass.setText("");
            tf_user.setText("");
        }
    }//GEN-LAST:event_btn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Crear;
    private javax.swing.JMenu Login;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_r_log;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDialog jd_Cexamen;
    private javax.swing.JDialog jd_Ctutor;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_estudiante;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_tutor;
    private javax.swing.JMenuItem jmi_Calumno;
    private javax.swing.JMenuItem jmi_Cexamen;
    private javax.swing.JMenuItem jmi_Ctutor;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
    ArrayList<Examen> examenes = new ArrayList();
    ArrayList<Tutor> tutor = new ArrayList();
    ArrayList<Anormal> estudiantes = new ArrayList();
}
